version: "3.7"

services:
  mongodb:
    image: mongo:latest
    restart: always
    container_name: mongodb
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./docker/mongodata:/mongodata
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pwd
      MONGO_INITDB_DATABASE: scoredb
    ports:
      - '27017:27017'

